### ISSUE TITLE
Difference between bigpose_vertices and tvertices

### ISSUE THREAD

**Issue by louhz** [zju3dv/instant-nvr#3]
Hi, i notice that when load for the v-shaped, the config states that we should load the bigpose_vertices instead of tvertices.
I am curious about the difference between this two file.
Can you share about the insight of this setting?

Thanks!

**Comment by louhz** [comment]
Also when i trained for sequence 393 based on the default setting, the training is finished in 5 min and the result looks like very bad in non-rigid clothes optimization And the hand is very blurry . 
Have you seen this circumstance before?
<img width="869" alt="screenshot 2023-06-21 183004" src="https://github.com/zju3dv/instant-nvr/assets/42707859/650fc2d2-6ac3-4d20-9364-cf279b2a720b">

**Comment by gcgeng** [comment]
1. The main distinction between the bigpose parameters and the t-pose parameters lies in the definition of canonical space. The bigpose parameters are based on the assumption that the canonical human pose resembles the Chinese character '大', while the t-pose parameters assume that the canonical human pose resembles the English character 'T'. In the bigpose, the legs are positioned apart, resulting in fewer artifacts between them. Please see the figures below for an intuitive explanation.
2. These artifacts can occasionally occur due to imprecise hand pose estimation, but they can be mitigated by employing more accurate hand pose estimation methods.

<img width="200" alt="image" src="https://github.com/zju3dv/instant-nvr/assets/8966584/7b3fa6af-03b0-4947-a06d-a49b41897909">
<br>
Fig. 1. Illustration of tpose (from the SMPL paper) 
<br>

<img width="200" alt="image" src="https://github.com/zju3dv/instant-nvr/assets/8966584/d4ad0fd0-44b7-44b9-b2fa-efe910bb7124"><br>
Fig. 2. Illustration of bigpose 
<br>
