### ISSUE TITLE
Question about transform view direction

### ISSUE THREAD

**Issue by QuLiao1117** [zju3dv/instant-nvr#8]
Hello,

Thank you for the excellent work you've shared here! I have a query concerning the necessity of transforming directions from the pose space to the T pose. May I ask what's the purpose of this step? Are there any potential drawbacks if we choose to omit this transformation process? Since I think optimizing two pose spaces with different view directions can reach similar results. 

Thank you in advance for your time and insights.
Best regards.

**Comment by gcgeng** [comment]
We follow the previous work Ani-SDF to take the design choice of transforming the view direction to canonical space. 

Theoretically, because our rendering function is defined in the canonical space, transforming the view direction into canonical space ensures diversity in radiance w.r.t. different local view directions.

Empirically, previous work shows that adding this can contribute to better rendering quality, as shown in Sec. 2.2 of https://arxiv.org/pdf/2203.08133.pdf

Please feel free to reopen the issue if you have any further questions.

Best,
Chen
